### PR TITLE
Closes #335

### LINKED ISSUE #335: [Windows 10, CMD.EXE] IOException: Cannot run program "/bin/stty": CreateProcess error=2
I'm trying to run this piece of code:

`Main.java`:
```java
package ru.saber_nyan.lanterna_bug;

import com.googlecode.lanterna.terminal.DefaultTerminalFactory;
import com.googlecode.lanterna.terminal.Terminal;

import java.io.PrintStream;

public final class Main {

	private static final PrintStream out = System.out;

	public static void main(String[] args) throws Throwable {
		out.println("OS name: " + System.getProperty("os.name"));
		Terminal terminal = new DefaultTerminalFactory().createTerminal();
		out.println("Created terminal (class " + terminal.getClass() + ")");
	}
}
```

`build.gradle`:
```gradle
group 'lanterna-bug'
version '0.0.1a'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.googlecode.lanterna:lanterna:3.0.0'
}

jar {
    manifest.attributes("Main-Class": "ru.saber_nyan.lanterna_bug.Main")
    from sourceSets.main.output, configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}
```

And after running in the usual command line (CMD.EXE), I get:
```cmd
D:\DEVELOPMENT_IS_MY_LAIFU\Workspaces\Java_Kotlin\lanterna-bug>gradlew jar
:compileJava
:processResources NO-SOURCE
:classes
:jar

BUILD SUCCESSFUL

Total time: 1.395 secs
D:\DEVELOPMENT_IS_MY_LAIFU\Workspaces\Java_Kotlin\lanterna-bug>java -jar .\build\libs\lanterna-bug-0.0.1a.jar
OS name: Windows 10
Exception in thread "main" java.io.IOException: Cannot run program "/bin/stty": CreateProcess error=2,
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.exec(UnixLikeTTYTerminal.java:169)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.saveTerminalSettings(UnixLikeTTYTerminal.java:117)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal.acquire(UnixLikeTerminal.java:86)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.realAcquire(UnixLikeTTYTerminal.java:87)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.<init>(UnixLikeTTYTerminal.java:78)
        at com.googlecode.lanterna.terminal.ansi.CygwinTerminal.<init>(CygwinTerminal.java:59)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createCygwinTerminal(DefaultTerminalFactory.java:416)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createWindowsTerminal(DefaultTerminalFactory.java:411)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createTerminal(DefaultTerminalFactory.java:117)
        at ru.saber_nyan.lanterna_bug.Main.main(Main.java:14)
Caused by: java.io.IOException: CreateProcess error=2,
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
```

```cmd
D:\DEVELOPMENT_IS_MY_LAIFU\Workspaces\Java_Kotlin\lanterna-bug>gradlew --version

------------------------------------------------------------
Gradle 3.5-rc-2
------------------------------------------------------------

Build time:   2017-03-27 15:56:23 UTC
Revision:     ec63970cd167993d3dcda346a1d00a286a23b1c9

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64
```

### PR DESCRIPTION
**Pull request by saber-nyan**

### CODE REVIEW

File: src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java [hunk 1]
```diff
@@ -408,7 +408,12 @@ private Terminal createWindowsTerminal() throws IOException {
             return (Terminal)constructor.newInstance(inputStream, outputStream, charset, UnixLikeTTYTerminal.CtrlCBehaviour.CTRL_C_KILLS_APPLICATION);
         }
         catch(Exception ignore) {
-            return createCygwinTerminal(outputStream, inputStream, charset);
+            try {
+                return createCygwinTerminal(outputStream, inputStream, charset);
+            } catch(IOException e) {
+                throw new IOException("To start java on Windows, use javaw!\n"
+                        + "(see https://github.com/mabe02/lanterna/issues/335 )", e);
```
Comment (RAnders00) [inline src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java]: Maybe use System.lineSeparator() instead of "\n" for better Windows support?

Comment (saber-nyan) [reply src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java]: Yes, of course, I forgot about it...

**Comment by mabe02** [comment]
@saber-nyan where did you get this link from?
image
